import assert from "node:assert/strict";
import { describe, test } from "node:test";

import { extractUserIntent, formatQueryStats, sanitizeRecallQuery, QUERY_MAX_CHARS } from "../index.js";

describe("extractUserIntent", () => {
  test("strips host reminder blocks that arrive inside the prompt field", () => {
    const { query, stats } = extractUserIntent(
      "<system-reminder>Remember to be concise.\nAlso load the skill.</system-reminder>\nhow do we rotate the agent token?",
    );
    assert.equal(query, "how do we rotate the agent token?");
    assert.ok(stats.removed.reminder > 0);
  });

  test("strips IDE selection panes", () => {
    const { query, stats } = extractUserIntent(
      "<ide_selection>func main() { fmt.Println(1) }</ide_selection> why does this panic?",
    );
    assert.equal(query, "why does this panic?");
    assert.ok(stats.removed.ide > 0);
  });

  test("strips expanded slash-command XML, not just a leading bare command", () => {
    const { query, stats } = extractUserIntent(
      "<command-name>/commit</command-name><command-message>commit is running</command-message>ship the memory fix",
    );
    assert.equal(query, "ship the memory fix");
    assert.ok(stats.removed.command > 0);
  });

  test("strips a bare leading slash command", () => {
    assert.equal(sanitizeRecallQuery("/ask what did we decide about v2?"), "what did we decide about v2?");
  });

  test("strips our own injected blocks so recall cannot search its own output", () => {
    const { query, stats } = extractUserIntent(
      "<everme_recall>- likes durian\n- prefers Go</everme_recall>\n<everme_profile>x</everme_profile>\nwhat is next on the roadmap?",
    );
    assert.equal(query, "what is next on the roadmap?");
    assert.ok(stats.removed.everme > 0);
  });

  test("strips a markdown-rendered EverMe Memory block", () => {
    const { query } = extractUserIntent("## EverMe Memory\n- likes durian\n\nplan the release train");
    assert.equal(query, "plan the release train");
  });

  test("strips the local-command caveat preamble", () => {
    const { query, stats } = extractUserIntent(
      "Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these.\nwhy is the flush timing out?",
    );
    assert.equal(query, "why is the flush timing out?");
    assert.ok(stats.removed.caveat > 0);
  });

  test("folds fenced code blocks to a marker instead of embedding the dump", () => {
    const dump = "```go\n" + "fmt.Println(1)\n".repeat(500) + "```";
    const { query, stats } = extractUserIntent(`${dump}\nwhat is wrong here?`);
    assert.ok(query.includes("what is wrong here?"));
    assert.ok(query.length < 60, `expected the dump to be folded, got ${query.length} chars`);
    assert.ok(stats.removed.code > 7000);
  });

  test("folds a long whitespace-free paste (base64, minified log line)", () => {
    const blob = "a".repeat(5000);
    const { query, stats } = extractUserIntent(`${blob} decode this please`);
    assert.ok(query.endsWith("decode this please"));
    assert.ok(stats.removed.paste > 4000);
    assert.ok(query.length < 500);
  });

  test("keeps the tail when clamping, because the question follows the context", () => {
    const noise = "context ".repeat(400); // > QUERY_MAX_CHARS of preamble
    const { query, stats } = extractUserIntent(`${noise}so what should we do about the 503s?`);
    assert.ok(stats.clamped);
    assert.ok(
      query.endsWith("so what should we do about the 503s?"),
      "the user's question must survive the clamp",
    );
    assert.ok(query.length <= QUERY_MAX_CHARS);
  });

  test("does not open the clamped query mid-token", () => {
    const { query } = extractUserIntent("x".repeat(50) + " " + "word ".repeat(400));
    assert.ok(!query.startsWith("ord"), "clamp starts on a word boundary");
  });

  test("leaves a clean short question untouched", () => {
    const { query, stats } = extractUserIntent("how does the release train work?");
    assert.equal(query, "how does the release train work?");
    assert.deepEqual(stats.removed, {});
    assert.equal(stats.clamped, false);
  });

  test("folds mixed-language whitespace like the previous sanitizer did", () => {
    assert.equal(sanitizeRecallQuery("  OAuth   design\tplan "), "OAuth design plan");
  });

  test("survives null and undefined", () => {
    assert.equal(sanitizeRecallQuery(null), "");
    assert.equal(sanitizeRecallQuery(undefined), "");
  });

  test("reports a real reduction on a realistic noisy prompt", () => {
    const prompt = [
      "<system-reminder>",
      "Codebase and user instructions are shown below.".repeat(80),
      "</system-reminder>",
      "<ide_selection>server/internal/biz/memory/search.go:58</ide_selection>",
      "```",
      "2026-07-30 08:30:47 ERROR core/core.go:44 api response error".repeat(60),
      "```",
      "why are we still getting 40501 on search?",
    ].join("\n");

    const { query, stats } = extractUserIntent(prompt);
    // Reminder + IDE panes vanish entirely; the log dump survives only as the
    // marker that says "the user pasted something here".
    assert.equal(query, "[...] why are we still getting 40501 on search?");
    assert.ok(stats.rawChars > 5000);
    assert.ok(stats.queryChars < 100);
    assert.equal(stats.clamped, false, "stripping alone is enough; no blind clamp needed");
  });
});

describe("formatQueryStats", () => {
  test("renders lengths and rule names, never the query text", () => {
    const { stats } = extractUserIntent("<system-reminder>secret guidance</system-reminder>hello there");
    const line = formatQueryStats(stats);
    assert.match(line, /^raw=\d+ query=\d+ clamped=false removed\{reminder:\d+\}$/);
    assert.ok(!line.includes("secret"));
    assert.ok(!line.includes("hello"));
  });

  test("orders rules by how much each removed", () => {
    const line = formatQueryStats({
      rawChars: 100,
      queryChars: 10,
      clamped: true,
      removed: { code: 10, reminder: 80 },
    });
    assert.equal(line, "raw=100 query=10 clamped=true removed{reminder:80,code:10}");
  });
});
