/**
 * Recall query extraction.
 *
 * A host hands us the whole prompt payload, not a question. Depending on the
 * host that payload carries framework context the user never typed: reminder
 * blocks, IDE selections, expanded slash commands, our own previously injected
 * memory block, caveat preambles, and pasted code or log dumps. All of it used
 * to travel into /mem/search as the query, where it does two kinds of damage:
 *
 *   1. Relevance: the embedding is dominated by boilerplate, so recall returns
 *      whatever matches the framework text rather than the user's intent.
 *   2. Loss: over the server's query cap the request was rejected outright
 *      (production: ~64 rejected searches a day), and clamping blindly from
 *      the head throws away the real question whenever noise precedes it.
 *
 * extractUserIntent strips the known framework shapes, folds bulk pastes down
 * to a marker, and clamps by keeping the END of what remains — the user's last
 * sentence is the intent, the preamble is context. It reports what it removed
 * so the effect is measurable end to end instead of being taken on faith.
 */

// One source of truth for the server's query cap: searchMemory owns it, we
// clamp against the same number so the query on the wire is the one we chose
// (tail-preserving) rather than searchMemory's head slice.
import { QUERY_MAX_CHARS } from "../search.js";

export { QUERY_MAX_CHARS };

// Bulk pastes are folded to a marker rather than removed: that the user pasted
// a diff or a log is weak signal, its 40 KB of content is pure noise.
const FOLD_MARKER = "[...]";
const MAX_PASTE_RUN_CHARS = 400;

// Every rule is (name, regex) so callers can log WHICH kind of framework noise
// a host is sending, not just that something was removed. Order matters:
// wrapper blocks run before line-level rules so their inner text never
// survives as an orphan.
const STRIP_RULES = [
  // Host reminder / context blocks. Claude Code, MiniMax Code and others wrap
  // injected guidance in these; MiniMax delivers them inside the prompt field
  // itself, so without this the reminder IS the query.
  ["reminder", /<system-reminder>[\s\S]*?<\/system-reminder>/gi],
  ["reminder", /<system_reminder>[\s\S]*?<\/system_reminder>/gi],
  // IDE panes: current selection / opened file context.
  ["ide", /<ide_selection>[\s\S]*?<\/ide_selection>/gi],
  ["ide", /<ide_opened_file>[\s\S]*?<\/ide_opened_file>/gi],
  // Expanded slash commands. The host replaces "/cmd args" with this XML, so
  // the leading-slash rule below can no longer see it.
  ["command", /<command-(?:name|message|args)>[\s\S]*?<\/command-(?:name|message|args)>/gi],
  // Our own injections coming back around. A host that echoes the previous
  // turn's user message would otherwise feed our memory block back in as the
  // next query, making recall search its own output.
  ["everme", /<everme_[a-z_]+>[\s\S]*?<\/everme_[a-z_]+>/gi],
  // No /m here: with it, `$` would match end-of-LINE and the block would stop
  // at its own heading, leaving the memory body in the query.
  ["everme", /(?:^|\n)#{1,3}[ \t]*EverMe Memory\b[\s\S]*?(?=\n[ \t]*\n|\n#{1,3}[ \t]|$)/gi],
  // Local-command caveat preamble (prepended to prompts that followed a bash
  // invocation).
  ["caveat", /^[ \t]*Caveat:[ \t]*The messages below were generated by the user while running local commands.*$/gim],
  // Attachment / tool-output envelopes some hosts inline.
  ["attachment", /<(?:attachment|tool_result|function_results)>[\s\S]*?<\/(?:attachment|tool_result|function_results)>/gi],
];

const LEADING_COMMAND_RE = /^\s*\/[^\s]+(?:\s+|$)/u;
const FENCED_CODE_RE = /```[\s\S]*?(?:```|$)/g;
const LONG_RUN_RE = /\S{400,}/gu;

/**
 * @param {string} text raw host prompt payload
 * @returns {{query: string, stats: {rawChars: number, queryChars: number, removed: Record<string, number>, clamped: boolean}}}
 *          `removed` maps rule name to the characters that rule dropped.
 */
export function extractUserIntent(text) {
  const raw = String(text ?? "");
  const removed = {};
  let working = raw;

  const drop = (name, next) => {
    const delta = working.length - next.length;
    if (delta > 0) removed[name] = (removed[name] || 0) + delta;
    working = next;
  };

  for (const [name, pattern] of STRIP_RULES) {
    drop(name, working.replace(pattern, " "));
  }
  drop("code", working.replace(FENCED_CODE_RE, ` ${FOLD_MARKER} `));
  drop("command", working.replace(LEADING_COMMAND_RE, ""));
  drop("paste", working.replace(LONG_RUN_RE, (run) => `${run.slice(0, MAX_PASTE_RUN_CHARS)} ${FOLD_MARKER}`));

  working = working.replace(/\s+/gu, " ").trim();

  let clamped = false;
  if (working.length > QUERY_MAX_CHARS) {
    // Keep the TAIL: framework context and pasted material sit in front of the
    // question, so the last sentence carries the intent. Start on a word
    // boundary so the query does not open mid-token.
    const tail = working.slice(working.length - QUERY_MAX_CHARS);
    const boundary = tail.search(/\s/);
    working = (boundary > 0 && boundary < 80 ? tail.slice(boundary + 1) : tail).trim();
    clamped = true;
  }

  return {
    query: working,
    stats: { rawChars: raw.length, queryChars: working.length, removed, clamped },
  };
}

/**
 * sanitizeRecallQuery is the published SDK surface and returns the query text
 * only. Prefer extractUserIntent where the caller can log the stats.
 */
export function sanitizeRecallQuery(text) {
  return extractUserIntent(text).query;
}

/**
 * formatQueryStats renders one operator-readable line:
 *   raw=8123 query=142 clamped=false removed{reminder:5400,code:2100}
 * Lengths only, never the text: a recall query carries user content.
 */
export function formatQueryStats(stats) {
  const removed = Object.entries(stats?.removed || {})
    .sort(([, a], [, b]) => b - a)
    .map(([name, chars]) => `${name}:${chars}`)
    .join(",");
  return `raw=${stats?.rawChars ?? 0} query=${stats?.queryChars ?? 0} clamped=${Boolean(stats?.clamped)} removed{${removed}}`;
}
